<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AquaParse\AquaParse.csproj" />
    <ProjectReference Include="..\LilyFS\LilyFS.csproj" />
    <ProjectReference Include="..\RuiSys\RuiSys.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
